# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(683, 393)
        self.centralwidget = QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame {    \n"
"background-color: rgb(244, 244, 244);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QRect(0, 40, 661, 101))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(1, 122, 255);")
        self.label_title.setAlignment(Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.progressBar = QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QRect(50, 280, 561, 23))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(229, 229, 229);\n"
"    color: rgb(35, 37, 38);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 122, 255);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QRect(0, 320, 661, 21))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(121, 121, 121);")
        self.label_loading.setAlignment(Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_credits = QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QRect(20, 350, 621, 21))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(121, 121, 121);")
        self.label_credits.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.label_current_version = QLabel(self.dropShadowFrame)
        self.label_current_version.setGeometry(QRect(0, 190, 661, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_current_version.setFont(font)
        self.label_current_version.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_current_version.setAlignment(Qt.AlignCenter)
        self.label_current_version.setOpenExternalLinks(False)
        self.label_current_version.setObjectName("label_current_version")
        self.label_actual_version = QLabel(self.dropShadowFrame)
        self.label_actual_version.setGeometry(QRect(0, 220, 661, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_actual_version.setFont(font)
        self.label_actual_version.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_actual_version.setAlignment(Qt.AlignCenter)
        self.label_actual_version.setWordWrap(False)
        self.label_actual_version.setObjectName("label_actual_version")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_title.setText(_translate("SplashScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Электронный каталог библиотеки<br/>МАОУ “Академический лицей” </span></p></body></html>"))
        self.label_loading.setText(_translate("SplashScreen", "loading..."))
        self.label_credits.setText(_translate("SplashScreen", "<strong>Created</strong>: Rozhkov M. E."))
        self.label_current_version.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Current version: </span>1.4</p></body></html>"))
        self.label_actual_version.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Actual version:</span></p></body></html>"))